Fix 5 npm dependencies (#42)
* Display exec path of non-python kernels (#7929)

* Add news entry for issue 7931 (#7932)

* Merge September point release (#7933)

* Group kernels in by kernel picker by Python environment type (#7930)

* Have a per interpreter language server in the jupyter extension (#7924)

* Get per language server running

* Using new middleware

* Turn off tracing and update to latest middleware

* Cache interpreter ids to make lookup faster

* Attempt at a reset on kernel change

* Handle switching the language server

* Make sure to tell new server when not created about a file

* Refactor IW test helpers

* Add some tests for switching

* Add news entry

* Update package-lock.json

* Disable interpreter switch when no interpreters

* Skip completion test for interactive

* Fix build error

* Code review feedback

* Cache promise instead of result

* Fix active interpreter in multi root scenarios

* Force pandas remove before checking its not there.

* Fixup test to more robust

* For now turn off language server for Python extension

* Start consolidation of repos

* Jupyter editor types fix for ipywidget build (#7942)

* fixup the clientrect issue

* added new and thanks

Co-authored-by: Ian Huff <ianhuff@Ians-MacBook-Pro.local>

* Re-run initialization when changing kernels in iw (#7948)

* Proper detect of active interpreter for controller (#7946)

* Export Refactor (#7939)

* Update area paths

* Notebook to list labels.

* Detect new virtual environments (#7969)

* Remove some dead code (#7963)

* Remove old kernel specs & backup into a folder (#7972)

* Check if users use conda env without different executables (#7973)

* Add aggregate-issue as base cat

* Do not load kernels from the backup folder (where old deleted kernels are backed up) (#7980)

* Added sanity checks for vscode repo

* trivial

* Fixes to Interactive Window restarts (#7984)

* Fixes to compiler issues resulting from types in @types/jsdom/default.d.ts (#7987)

* Leaner INotebook (#7979)

* Revert commit related to PR https://github.com/microsoft/vscode-jupyter/pull/7984 (#7988)

* Fixes to Interactive window __file__ tests (#7989)

* Remove dup kernel & ensure global kernels point to the right interpreter (#7996)

* Improve ipywidgets performance by synchronizing only output widgets state changes (#7959)

* Add news entry for 7965 (#8000)

* Update package.nls.zh-tw.json with translations (#7956)

* Minor updates

* Fix Proposed API (#8006)

* update api

* update MockStatusBarItem

Co-authored-by: Ian Huff <ianhuff@Ians-MacBook-Pro.local>

* Plain Python Export (#7998)

* Categorize controllers (#7981)

* Add controller categories

* fix formatting

* fix formatting

* misc

* fix formatting

* misc

* Misc

* remove controllers and add them back

* misc

* fixes to compiler issuees

* fix formatting

* fix formatting

* fixes to compiler issuees

* fix formatting

* misc

* misc

* misc

* fix formatting

* fixes

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* Hide toolbar icons if not using Python notebooks (#8010)

* Support for semantic tokens in notebooks (#8001)

* Interpreter id was getting dupes

* Add a test update waitForCondition to not continually spam for the promise

* JediLSP isn't a thing

* Update to latest npm middleware

* Add news entry

* Update to latest and support intellisense in interactive

* Disable semantic token test

* Store kernel language in the `ipynb` metadata (#8027)

* Add support for jupyter autocomplete back to the IW (#8035)

* Add support for jupyter autocomplete back to the IW

* Update linter

* notebook-workflow

* notebook-execution label

* Fix IW debugging for ipykernel 6.2 (#8038)

* Fix IW debugging for ipykernel 6.2

* Add news entry

* Update filter placeholder text (#8049)

* Fix lable for virtual Env (#8056)

* Add setting jupyter.newCellOnRunLast (#7995)

* add setting jupyter.newCellOnRunLast

* fix CI error TS2420: Property 'newCellOnRunLast' is missing in type 'JupyterSettings' but required in type 'IWatchableJupyterSettings'

* Create 7966.md

* Fix cell debugging for IW with ipykernel 5 (#8073)

* Update category name for Pyenv envs (#8072)

* Suppress save before debugging cell (#8074)

* Make sure 'stop cell' for IW debugging actually interrupts (#8070)

* Make sure 'stop cell' for IW debugging actually interrupts

* Add news entry

* Change to kernel promise

* Hide toolbar when as non-jupyter kernel is picked (#8086)

* Don't throw away the display_name for python kernel specs (#8077)

* Tweaks

* Wait on iopub and send kernel info request (#8090)

* Fix problem with breakpoints in previous cells (#8091)

* Fix problem with breakpoints in previous cells

* Cleanup and review feedback

* Get rid of async problem in event handler

* Review feedback

* Make sure to only do hashes on IW

* Fix merge problems

* Update codeql-analysis.yml (#8094)

Comment out code-ql, it's failing with permissions problems.

* Avoid losing ipywidgets kernel communications when switching kernel (#8096)

Co-authored-by: Don Jayamanne <don.jayamanne@outlook.com>

* Add aggregate-issues housekeeping

* Ensure we uncomment magics when generating cell hashes (#8097)

* Disable insiders

* Add release required items (#8101) (#8102)

* Fix up changelog

* Update 3rd party distribution

* Update engine version

* Update change logs

Co-authored-by: Don Jayamanne <don.jayamanne@outlook.com>

Co-authored-by: Don Jayamanne <don.jayamanne@outlook.com>

* Update release_plan.md

* Fix flakiness of debugger tests. They don't need to show an interrupt, just have to finish debugging (#8103)

* Update to latest middleware with token edit fix (#8105)

* Update build-test.yml (#8109)

Following directions here.
https://github.com/marketplace/actions/cancel-workflow-action

* Update release_plan.md

* Improvements to logging (#8098)

* Support interrupting non-python kernels (#8125)

* Update test_plan.md

* Clean IJupyterSession & INotebook, Remove IKernel.notebook (#8104)

* Add a bunch of debugger tests for IW (#8128)

* Add a bunch of debugger tests for IW

* Remove debugger functional test as superseded now

* Try caching conda to speed up install steps (#8129)

* Attempt conda caching

* Consolidate conda install

* Uses doesn't work with run

* Ignore events from IJupyterSession if its not the active session (#8127)

* Update test_plan.md

* Update run by line interrupt test (#8135)

* Fix export interactive as jupyter notebook (#8137)

* Remove kernel finder from server start (#8133)

* Update package.json

* Add setting for supporting pylance handling notebook intellisense (#8140)

* Refactor IJupyterSession restarts & constructors (#8147)

* Cleanup restarts

* fix formatting

* Remove kernelspec when starting server (#8144)

* Display better error when raw kernel times out connecting to kernel (#8145)

* Display better error when timingout

* fix formatting

* Add action to check for telemetry changes (#8154)

* Add action to check for telemetry changes

* Update build-test.yml

* Remove KernelSpecNotFound error and related code (dead code) (#8152)

* Take in fix for 5932 (#8153)

* Fixes related to handling carriage return (#8139)

* Fixes related to handling carriage return

* fix test

* fix formatting

* fix linter

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* fix formatting

* Improvements related to handling of dead kernels (#8156)

* Remove caching of INotebook (#8161)

* Move Error classes into errors folder (#8165)

* Import ipynb commands (command and right click file menu) use pythonExportMethod setting (#8163)

* Update main after release (#8167)

* Rchiodo/fix build vsix (#8118)

* Support dispatch for release build

* Typo

* Update to latest middleware with token edit fix (#8105)

* Lot and check if we fail to get activated env variables (#8142)

* Update for post release

* Bump version number

* Update package-lock.json

* Fix merge error

Co-authored-by: Don Jayamanne <don.jayamanne@outlook.com>

* set global jupyter interpreter on nbconvert export and make sure to load vscode ipynb extension (#8180)

Co-authored-by: Ian Huff <ianhuff@Ians-MacBook-Pro.local>

* Display notebook paths in kernel picker for remote kernels (#8181)

* Support ipywidgets for live kernels (#8184)

* Better error messages when kernel fails (#8171)

* Remove unnecessary welcome notification (#8192)

* Ensure we display the original ipynb file name in kernel picker (#8187)

* No prompts to install python when opening .NET nb (#8206)

* Update dates and add VS Code repo triage

* Try newer node (#8216)

* Try newer node

* Update .github/workflows/build-test.yml

Co-authored-by: Don Jayamanne <don.jayamanne@outlook.com>

* Fix proposed api check

Co-authored-by: Don Jayamanne <don.jayamanne@outlook.com>

* First crack at documenting VS Code Stable / Jupyter Extension version matching (#8211)

* Add version match table
Generated by manually installing multiple older builds of VS Code stable
and checking the minimum installable version of Jupyter is.
Right click on extension and choose "Install Another Version..."

* Clarify base version with bold

* Update proposed API (#8218)

* Install pip when missing to support installation of missing packages (#8205)

* Upgrade to new lsp middleware concat (#8219)

* Handle changes from middleware

* Make sure to fire selection change when updating affinity

* Update to latest lsp middleware

* Try upping .NET version

* Try new .net again

* Fix .net and try a different way to track selected controllers

* Fix taskGroup (#8221)

* Update CONTRIBUTING.md

added Windows command for activating python venv

* Fix proposed changes again (#8222)

* Fix flakey run by line test (#8234)

* Try fixing the debugger run by line test

* Fix run by line test to behave more consistently

* Warn when using unsupported python kernel versions (#8214)

* Stop starting default kernel when starting jupyter (#8238)

* Better error handling when kernel crashes due to overridden built in modules (#8237)

* Improve jupyter kernel autocompletions (#8247)

* Fix jupyter autocomplete to filter a bunch of stuff

* Add a bunch of tests

* Add news items and update tests

* Put mock document back

* Renaming and other review feedback

* Review feedback

* Update configSettings.ts

* Update to fix for diags in notebooks (#8251)

* Update to fix for diags in notebooks

* Take fix for IW too

* Set theme jekyll-theme-cayman

* feat: upgrade multiple dependencies with Snyk

Snyk has created this PR to upgrade:
  - react from 16.8.6 to 17.0.2.
    See this package in npm: https://www.npmjs.com/package/react
  - react-dom from 16.8.6 to 17.0.2.
    See this package in npm: https://www.npmjs.com/package/react-dom

See this project in Snyk:
https://app.snyk.io/org/brand-new/project/1399564f-96db-414c-9ab6-a721c1a0ddab?utm_source=github&utm_medium=referral&page=upgrade-pr

* Fix 5 npm dependencies

npm audit fix updated the following npm dependencies:

 * follow-redirects > 1.14.7
 * jquery-ui > 1.13.1
 * jsprim > 1.4.2
 * log4js > 6.4.1
 * node-fetch > 2.6.7

[atomist:generated]
[atomist-skill:atomist/npm-vulnerability-scanner-skill]

Co-authored-by: Don Jayamanne <don.jayamanne@outlook.com>
Co-authored-by: Rich Chiodo <rchiodo@users.noreply.github.com>
Co-authored-by: greazer <jimgries@microsoft.com>
Co-authored-by: Ian Huff <ianhu@microsoft.com>
Co-authored-by: Ian Huff <ianhuff@Ians-MacBook-Pro.local>
Co-authored-by: sdissegna-maystreet <89396746+sdissegna-maystreet@users.noreply.github.com>
Co-authored-by: ted1030 <htl8610@gmail.com>
Co-authored-by: Jim Griesmer <jimgpub@live.com>
Co-authored-by: Janosh Riebesell <janosh.riebesell@gmail.com>
Co-authored-by: Kim-Adeline Miguel <51720070+kimadeline@users.noreply.github.com>
Co-authored-by: Rob Lourens <roblourens@gmail.com>
Co-authored-by: Aaron Munger <aamunger@microsoft.com>
Co-authored-by: Jacquelyn Vinson <jacqvinson@gmail.com>
Co-authored-by: snyk-bot <snyk-bot@snyk.io>
Co-authored-by: Atomist Bot <bot@atomist.com>